/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajoutexcurssionarijmtar (void);
GtkWidget* create_modifexcurssionarij (void);
GtkWidget* create_excurssionmodarij (void);
