/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include<stdio.h>
#include<string.h>
#include<stdlib.h>

#include "interface.h"
#include "support.h"
#include "excur.h"

int
main (int argc, char *argv[])
{
  GtkWidget *ajoutexcurssionarijmtar;
 GtkWidget *wafa;
GtkWidget *modifexcurssionarij;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
   modifexcurssionarij = create_modifexcurssionarij ();
  gtk_widget_show (modifexcurssionarij);
wafa=lookup_widget(modifexcurssionarij,"wafa");

afficher_excur(wafa);

  gtk_main ();
  return 0;
}

