/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *fixed2;
  GtkWidget *compagnie_aerienne;
  GtkWidget *destination;
  GtkWidget *depart;
  GtkWidget *tarif;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkObject *num_vol_adj;
  GtkWidget *num_vol;
  GtkWidget *affichera;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image18;
  GtkWidget *label92;
  GtkWidget *label7;
  GtkWidget *label12;
  GtkWidget *label9;
  GtkWidget *label11;
  GtkWidget *label10;
  GtkWidget *classe;
  GtkWidget *label6;
  GtkWidget *label4;
  GtkWidget *label3;
  GtkWidget *num_vol0;
  GtkWidget *label2;
  GtkWidget *label95;
  GtkWidget *label100;
  GtkWidget *label101;
  GtkWidget *label102;
  GtkWidget *label103;
  GtkWidget *label105;
  GtkWidget *label104;
  GtkWidget *ajouter;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image17;
  GtkWidget *label91;
  GtkWidget *label1;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_fixed_put (GTK_FIXED (fixed1), fixed2, 200, 32);
  gtk_widget_set_size_request (fixed2, 50, 50);

  compagnie_aerienne = gtk_entry_new ();
  gtk_widget_show (compagnie_aerienne);
  gtk_fixed_put (GTK_FIXED (fixed2), compagnie_aerienne, 0, 64);
  gtk_widget_set_size_request (compagnie_aerienne, 155, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (compagnie_aerienne), 8226);

  destination = gtk_entry_new ();
  gtk_widget_show (destination);
  gtk_fixed_put (GTK_FIXED (fixed1), destination, 520, 96);
  gtk_widget_set_size_request (destination, 155, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (destination), 8226);

  depart = gtk_entry_new ();
  gtk_widget_show (depart);
  gtk_fixed_put (GTK_FIXED (fixed1), depart, 200, 176);
  gtk_widget_set_size_request (depart, 155, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (depart), 8226);

  tarif = gtk_entry_new ();
  gtk_widget_show (tarif);
  gtk_fixed_put (GTK_FIXED (fixed1), tarif, 352, 312);
  gtk_widget_set_size_request (tarif, 155, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (tarif), 8226);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed1), jour, 272, 256);
  gtk_widget_set_size_request (jour, 60, 27);

  mois_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed1), mois, 392, 256);
  gtk_widget_set_size_request (mois, 60, 27);

  annee_adj = gtk_adjustment_new (1, 2015, 2031, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed1), annee, 536, 256);
  gtk_widget_set_size_request (annee, 60, 27);

  num_vol_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  num_vol = gtk_spin_button_new (GTK_ADJUSTMENT (num_vol_adj), 1, 0);
  gtk_widget_show (num_vol);
  gtk_fixed_put (GTK_FIXED (fixed1), num_vol, 704, 24);
  gtk_widget_set_size_request (num_vol, 60, 27);

  affichera = gtk_button_new ();
  gtk_widget_show (affichera);
  gtk_fixed_put (GTK_FIXED (fixed1), affichera, 648, 384);
  gtk_widget_set_size_request (affichera, 120, 37);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (affichera), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox16), image18, FALSE, FALSE, 0);

  label92 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label92);
  gtk_box_pack_start (GTK_BOX (hbox16), label92, FALSE, FALSE, 0);

  label7 = gtk_label_new (_("Tarif :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 224, 312);
  gtk_widget_set_size_request (label7, 169, 25);

  label12 = gtk_label_new (_("Date_d\303\251part :"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed1), label12, 56, 256);
  gtk_widget_set_size_request (label12, 169, 24);

  label9 = gtk_label_new (_("Jour"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 208, 256);
  gtk_widget_set_size_request (label9, 75, 24);

  label11 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed1), label11, 456, 256);
  gtk_widget_set_size_request (label11, 75, 24);

  label10 = gtk_label_new (_("mois"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed1), label10, 328, 256);
  gtk_widget_set_size_request (label10, 75, 24);

  classe = gtk_combo_box_entry_new_text ();
  gtk_widget_show (classe);
  gtk_fixed_put (GTK_FIXED (fixed1), classe, 520, 176);
  gtk_widget_set_size_request (classe, 155, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (classe), _("firstclasse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (classe), _("economique"));

  label6 = gtk_label_new (_("Classe :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 408, 184);
  gtk_widget_set_size_request (label6, 113, 24);

  label4 = gtk_label_new (_("D\303\251part :"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 48, 176);
  gtk_widget_set_size_request (label4, 129, 25);

  label3 = gtk_label_new (_("Destination :"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 368, 104);
  gtk_widget_set_size_request (label3, 169, 24);

  num_vol0 = gtk_label_new (_("num_vol :"));
  gtk_widget_show (num_vol0);
  gtk_fixed_put (GTK_FIXED (fixed1), num_vol0, 568, 24);
  gtk_widget_set_size_request (num_vol0, 169, 24);

  label2 = gtk_label_new (_("Compagnie_aerienne :"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 16, 104);
  gtk_widget_set_size_request (label2, 169, 24);

  label95 = gtk_label_new ("");
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed1), label95, 472, 352);
  gtk_widget_set_size_request (label95, 160, 33);

  label100 = gtk_label_new ("");
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed1), label100, 192, 136);
  gtk_widget_set_size_request (label100, 168, 24);

  label101 = gtk_label_new ("");
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed1), label101, 520, 136);
  gtk_widget_set_size_request (label101, 168, 25);

  label102 = gtk_label_new ("");
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixed1), label102, 208, 224);
  gtk_widget_set_size_request (label102, 136, 17);

  label103 = gtk_label_new ("");
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed1), label103, 528, 224);
  gtk_widget_set_size_request (label103, 152, 17);

  label105 = gtk_label_new ("");
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed1), label105, 520, 312);
  gtk_widget_set_size_request (label105, 120, 25);

  label104 = gtk_label_new ("");
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed1), label104, 616, 256);
  gtk_widget_set_size_request (label104, 120, 25);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter, 496, 384);
  gtk_widget_set_size_request (ajouter, 120, 37);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment15);
  gtk_widget_set_size_request (alignment15, 76, 17);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image17 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox15), image17, FALSE, FALSE, 0);

  label91 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label91);
  gtk_box_pack_start (GTK_BOX (hbox15), label91, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("Bienvenue dans votre espace Agent"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 248, 8);
  gtk_widget_set_size_request (label1, 336, 48);

  g_signal_connect ((gpointer) affichera, "clicked",
                    G_CALLBACK (on_affichera_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, compagnie_aerienne, "compagnie_aerienne");
  GLADE_HOOKUP_OBJECT (window1, destination, "destination");
  GLADE_HOOKUP_OBJECT (window1, depart, "depart");
  GLADE_HOOKUP_OBJECT (window1, tarif, "tarif");
  GLADE_HOOKUP_OBJECT (window1, jour, "jour");
  GLADE_HOOKUP_OBJECT (window1, mois, "mois");
  GLADE_HOOKUP_OBJECT (window1, annee, "annee");
  GLADE_HOOKUP_OBJECT (window1, num_vol, "num_vol");
  GLADE_HOOKUP_OBJECT (window1, affichera, "affichera");
  GLADE_HOOKUP_OBJECT (window1, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window1, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window1, image18, "image18");
  GLADE_HOOKUP_OBJECT (window1, label92, "label92");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, label12, "label12");
  GLADE_HOOKUP_OBJECT (window1, label9, "label9");
  GLADE_HOOKUP_OBJECT (window1, label11, "label11");
  GLADE_HOOKUP_OBJECT (window1, label10, "label10");
  GLADE_HOOKUP_OBJECT (window1, classe, "classe");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, num_vol0, "num_vol0");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label95, "label95");
  GLADE_HOOKUP_OBJECT (window1, label100, "label100");
  GLADE_HOOKUP_OBJECT (window1, label101, "label101");
  GLADE_HOOKUP_OBJECT (window1, label102, "label102");
  GLADE_HOOKUP_OBJECT (window1, label103, "label103");
  GLADE_HOOKUP_OBJECT (window1, label105, "label105");
  GLADE_HOOKUP_OBJECT (window1, label104, "label104");
  GLADE_HOOKUP_OBJECT (window1, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (window1, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window1, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window1, image17, "image17");
  GLADE_HOOKUP_OBJECT (window1, label91, "label91");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed3;
  GtkWidget *treeview1;
  GtkObject *num_adj;
  GtkWidget *num;
  GtkWidget *label8;
  GtkWidget *ajoutera;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image21;
  GtkWidget *label97;
  GtkWidget *button3;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image14;
  GtkWidget *label87;
  GtkWidget *supprimer;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image20;
  GtkWidget *label96;
  GtkWidget *actualisation;
  GtkWidget *image19;
  GtkWidget *label89;
  GtkWidget *label94;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window2, 873, 362);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window2), fixed3);
  gtk_widget_set_size_request (fixed3, 873, 362);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 32, 56);
  gtk_widget_set_size_request (treeview1, 768, 208);

  num_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  num = gtk_spin_button_new (GTK_ADJUSTMENT (num_adj), 1, 0);
  gtk_widget_show (num);
  gtk_fixed_put (GTK_FIXED (fixed3), num, 736, 272);
  gtk_widget_set_size_request (num, 60, 27);

  label8 = gtk_label_new (_("Bienvenue dans votre espace Agent"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed3), label8, 304, 8);
  gtk_widget_set_size_request (label8, 344, 40);

  ajoutera = gtk_button_new ();
  gtk_widget_show (ajoutera);
  gtk_fixed_put (GTK_FIXED (fixed3), ajoutera, 136, 304);
  gtk_widget_set_size_request (ajoutera, 120, 37);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (ajoutera), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image21 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox18), image21, FALSE, FALSE, 0);

  label97 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label97);
  gtk_box_pack_start (GTK_BOX (hbox18), label97, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed3), button3, 312, 304);
  gtk_widget_set_size_request (button3, 120, 37);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button3), alignment12);
  gtk_widget_set_size_request (alignment12, 76, 17);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox12), image14, FALSE, FALSE, 0);

  label87 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox12), label87, FALSE, FALSE, 0);

  supprimer = gtk_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), supprimer, 488, 304);
  gtk_widget_set_size_request (supprimer, 120, 37);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image20 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox17), image20, FALSE, FALSE, 0);

  label96 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox17), label96, FALSE, FALSE, 0);

  actualisation = gtk_button_new ();
  gtk_widget_show (actualisation);
  gtk_fixed_put (GTK_FIXED (fixed3), actualisation, 632, 304);
  gtk_widget_set_size_request (actualisation, 120, 37);

  image19 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_container_add (GTK_CONTAINER (actualisation), image19);

  label89 = gtk_label_new (_("num_vol :"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed3), label89, 656, 272);
  gtk_widget_set_size_request (label89, 81, 17);

  label94 = gtk_label_new ("");
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed3), label94, 464, 272);
  gtk_widget_set_size_request (label94, 161, 33);

  g_signal_connect ((gpointer) ajoutera, "clicked",
                    G_CALLBACK (on_ajoutera_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) actualisation, "clicked",
                    G_CALLBACK (on_actualisation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window2, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window2, num, "num");
  GLADE_HOOKUP_OBJECT (window2, label8, "label8");
  GLADE_HOOKUP_OBJECT (window2, ajoutera, "ajoutera");
  GLADE_HOOKUP_OBJECT (window2, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window2, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window2, image21, "image21");
  GLADE_HOOKUP_OBJECT (window2, label97, "label97");
  GLADE_HOOKUP_OBJECT (window2, button3, "button3");
  GLADE_HOOKUP_OBJECT (window2, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window2, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window2, image14, "image14");
  GLADE_HOOKUP_OBJECT (window2, label87, "label87");
  GLADE_HOOKUP_OBJECT (window2, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (window2, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window2, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window2, image20, "image20");
  GLADE_HOOKUP_OBJECT (window2, label96, "label96");
  GLADE_HOOKUP_OBJECT (window2, actualisation, "actualisation");
  GLADE_HOOKUP_OBJECT (window2, image19, "image19");
  GLADE_HOOKUP_OBJECT (window2, label89, "label89");
  GLADE_HOOKUP_OBJECT (window2, label94, "label94");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed4;
  GtkWidget *fixed5;
  GtkWidget *compagnie_aeriennea;
  GtkWidget *destinationa;
  GtkWidget *departa;
  GtkWidget *tarifa;
  GtkObject *num_vola_adj;
  GtkWidget *num_vola;
  GtkWidget *modifiera;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label84;
  GtkWidget *label83;
  GtkWidget *label73;
  GtkWidget *classea;
  GtkWidget *joura;
  GtkWidget *anneea;
  GtkWidget *moisa;
  GtkWidget *valider;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image23;
  GtkWidget *label99;
  GtkWidget *debut;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image22;
  GtkWidget *label98;
  GtkWidget *label21;
  GtkWidget *label20;
  GtkWidget *label19;
  GtkWidget *label13;
  GtkWidget *label17;
  GtkWidget *label16;
  GtkWidget *label22;
  GtkWidget *label18;
  GtkWidget *label15;
  GtkWidget *label14;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window3), fixed4);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_fixed_put (GTK_FIXED (fixed4), fixed5, 200, 32);
  gtk_widget_set_size_request (fixed5, 50, 50);

  compagnie_aeriennea = gtk_entry_new ();
  gtk_widget_show (compagnie_aeriennea);
  gtk_fixed_put (GTK_FIXED (fixed5), compagnie_aeriennea, 56, 40);
  gtk_widget_set_size_request (compagnie_aeriennea, 155, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (compagnie_aeriennea), 8226);

  destinationa = gtk_entry_new ();
  gtk_widget_show (destinationa);
  gtk_fixed_put (GTK_FIXED (fixed4), destinationa, 616, 72);
  gtk_widget_set_size_request (destinationa, 155, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (destinationa), 8226);

  departa = gtk_entry_new ();
  gtk_widget_show (departa);
  gtk_fixed_put (GTK_FIXED (fixed4), departa, 256, 136);
  gtk_widget_set_size_request (departa, 155, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (departa), 8226);

  tarifa = gtk_entry_new ();
  gtk_widget_show (tarifa);
  gtk_fixed_put (GTK_FIXED (fixed4), tarifa, 432, 272);
  gtk_widget_set_size_request (tarifa, 155, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (tarifa), 8226);

  num_vola_adj = gtk_adjustment_new (2, 1, 100, 1, 10, 10);
  num_vola = gtk_spin_button_new (GTK_ADJUSTMENT (num_vola_adj), 1, 0);
  gtk_widget_show (num_vola);
  gtk_fixed_put (GTK_FIXED (fixed4), num_vola, 712, 24);
  gtk_widget_set_size_request (num_vola, 60, 27);

  modifiera = gtk_button_new ();
  gtk_widget_show (modifiera);
  gtk_fixed_put (GTK_FIXED (fixed4), modifiera, 624, 328);
  gtk_widget_set_size_request (modifiera, 120, 37);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (modifiera), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label84 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label84);
  gtk_box_pack_start (GTK_BOX (hbox9), label84, FALSE, FALSE, 0);

  label83 = gtk_label_new (_("num_vol"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed4), label83, 608, 24);
  gtk_widget_set_size_request (label83, 89, 25);

  label73 = gtk_label_new ("");
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed4), label73, 608, 296);
  gtk_widget_set_size_request (label73, 161, 25);

  classea = gtk_entry_new ();
  gtk_widget_show (classea);
  gtk_fixed_put (GTK_FIXED (fixed4), classea, 616, 144);
  gtk_widget_set_size_request (classea, 155, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (classea), 8226);

  joura = gtk_entry_new ();
  gtk_widget_show (joura);
  gtk_fixed_put (GTK_FIXED (fixed4), joura, 376, 208);
  gtk_widget_set_size_request (joura, 50, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (joura), 8226);

  anneea = gtk_entry_new ();
  gtk_widget_show (anneea);
  gtk_fixed_put (GTK_FIXED (fixed4), anneea, 664, 208);
  gtk_widget_set_size_request (anneea, 50, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (anneea), 8226);

  moisa = gtk_entry_new ();
  gtk_widget_show (moisa);
  gtk_fixed_put (GTK_FIXED (fixed4), moisa, 520, 208);
  gtk_widget_set_size_request (moisa, 50, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (moisa), 8226);

  valider = gtk_button_new ();
  gtk_widget_show (valider);
  gtk_fixed_put (GTK_FIXED (fixed4), valider, 784, 16);
  gtk_widget_set_size_request (valider, 120, 37);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (valider), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image23 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox20), image23, FALSE, FALSE, 0);

  label99 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label99);
  gtk_box_pack_start (GTK_BOX (hbox20), label99, FALSE, FALSE, 0);

  debut = gtk_button_new ();
  gtk_widget_show (debut);
  gtk_fixed_put (GTK_FIXED (fixed4), debut, 768, 328);
  gtk_widget_set_size_request (debut, 120, 37);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (debut), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image22 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox19), image22, FALSE, FALSE, 0);

  label98 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label98);
  gtk_box_pack_start (GTK_BOX (hbox19), label98, FALSE, FALSE, 0);

  label21 = gtk_label_new (_("Jour :"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 320, 208);
  gtk_widget_set_size_request (label21, 41, 17);

  label20 = gtk_label_new (_("mois :"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 456, 208);
  gtk_widget_set_size_request (label20, 49, 17);

  label19 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 600, 208);
  gtk_widget_set_size_request (label19, 49, 17);

  label13 = gtk_label_new (_("Compagnie_aerienne :"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed4), label13, 80, 80);
  gtk_widget_set_size_request (label13, 180, 30);

  label17 = gtk_label_new (_("Classe :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 488, 144);
  gtk_widget_set_size_request (label17, 180, 30);

  label16 = gtk_label_new (_("D\303\251part :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 120, 144);
  gtk_widget_set_size_request (label16, 180, 30);

  label22 = gtk_label_new (_("Date_d\303\251part :"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 152, 208);
  gtk_widget_set_size_request (label22, 180, 30);

  label18 = gtk_label_new (_("Tarif :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 304, 272);
  gtk_widget_set_size_request (label18, 180, 30);

  label15 = gtk_label_new (_("Destination :"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 472, 72);
  gtk_widget_set_size_request (label15, 180, 30);

  label14 = gtk_label_new (_("Bienvenue dans votre espace Agent"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 280, 8);
  gtk_widget_set_size_request (label14, 400, 40);

  g_signal_connect ((gpointer) modifiera, "clicked",
                    G_CALLBACK (on_modifiera_clicked),
                    NULL);
  g_signal_connect ((gpointer) valider, "clicked",
                    G_CALLBACK (on_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) debut, "clicked",
                    G_CALLBACK (on_debut_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window3, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window3, compagnie_aeriennea, "compagnie_aeriennea");
  GLADE_HOOKUP_OBJECT (window3, destinationa, "destinationa");
  GLADE_HOOKUP_OBJECT (window3, departa, "departa");
  GLADE_HOOKUP_OBJECT (window3, tarifa, "tarifa");
  GLADE_HOOKUP_OBJECT (window3, num_vola, "num_vola");
  GLADE_HOOKUP_OBJECT (window3, modifiera, "modifiera");
  GLADE_HOOKUP_OBJECT (window3, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window3, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window3, image9, "image9");
  GLADE_HOOKUP_OBJECT (window3, label84, "label84");
  GLADE_HOOKUP_OBJECT (window3, label83, "label83");
  GLADE_HOOKUP_OBJECT (window3, label73, "label73");
  GLADE_HOOKUP_OBJECT (window3, classea, "classea");
  GLADE_HOOKUP_OBJECT (window3, joura, "joura");
  GLADE_HOOKUP_OBJECT (window3, anneea, "anneea");
  GLADE_HOOKUP_OBJECT (window3, moisa, "moisa");
  GLADE_HOOKUP_OBJECT (window3, valider, "valider");
  GLADE_HOOKUP_OBJECT (window3, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window3, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window3, image23, "image23");
  GLADE_HOOKUP_OBJECT (window3, label99, "label99");
  GLADE_HOOKUP_OBJECT (window3, debut, "debut");
  GLADE_HOOKUP_OBJECT (window3, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window3, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window3, image22, "image22");
  GLADE_HOOKUP_OBJECT (window3, label98, "label98");
  GLADE_HOOKUP_OBJECT (window3, label21, "label21");
  GLADE_HOOKUP_OBJECT (window3, label20, "label20");
  GLADE_HOOKUP_OBJECT (window3, label19, "label19");
  GLADE_HOOKUP_OBJECT (window3, label13, "label13");
  GLADE_HOOKUP_OBJECT (window3, label17, "label17");
  GLADE_HOOKUP_OBJECT (window3, label16, "label16");
  GLADE_HOOKUP_OBJECT (window3, label22, "label22");
  GLADE_HOOKUP_OBJECT (window3, label18, "label18");
  GLADE_HOOKUP_OBJECT (window3, label15, "label15");
  GLADE_HOOKUP_OBJECT (window3, label14, "label14");

  return window3;
}

