/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1anouer (void);
GtkWidget* create_window2anouer (void);
GtkWidget* create_window3anouer (void);
GtkWidget* create_window4anouer (void);
GtkWidget* create_window5anouer (void);
GtkWidget* create_window6anouer (void);
GtkWidget* create_window7anouer (void);
GtkWidget* create_window8anouer (void);
GtkWidget* create_window9anouer (void);
GtkWidget* create_window10anouer (void);
